#pragma once

enum class OperationCode
{
	STOP,
	CHECK_SIZE,
    CHECK_EMAIL,
    CHECK_LOGIN,
	REGISTRATION,
	SIGN_IN,
    NEW_MESSAGES_IN_COMMON_CHAT,
	GET_NUMBER_MESSAGES_IN_CHAT,
	COMMON_CHAT_GET_MESSAGES,
	COMMON_CHAT_ADD_MESSAGE,
    COMMON_CHAT_CHECK_MESSAGE,
    COMMON_CHAT_EDIT_MESSAGE,
    COMMON_CHAT_DELETE_MESSAGE,
    VIEW_USERS_ID_NAME_SURNAME,
    GET_PRIVATE_CHAT_ID,
    PRIVATE_CHAT_ADD_MESSAGE,
	READY,
	NET_ERROR,
};

const int HEADER_SIZE = 256;
